# Generated by Django 4.0.1 on 2022-01-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songname',
            new_name='name',
        ),
    ]
